/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WordsRouteImport } from './routes/words'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SentencesDailyUseRouteImport } from './routes/sentences.daily-use'
import { Route as AuthenticatedTestRouteImport } from './routes/_authenticated/test'
import { Route as AuthenticatedPracticeRouteImport } from './routes/_authenticated/practice'
import { Route as AuthenticatedMySentencesRouteImport } from './routes/_authenticated/my-sentences'
import { Route as AuthenticatedMyMeaningsRouteImport } from './routes/_authenticated/my-meanings'
import { Route as AuthenticatedAdminMeaningsRouteImport } from './routes/_authenticated/admin/meanings'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const WordsRoute = WordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SentencesDailyUseRoute = SentencesDailyUseRouteImport.update({
  id: '/sentences/daily-use',
  path: '/sentences/daily-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTestRoute = AuthenticatedTestRouteImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPracticeRoute = AuthenticatedPracticeRouteImport.update({
  id: '/practice',
  path: '/practice',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMySentencesRoute =
  AuthenticatedMySentencesRouteImport.update({
    id: '/my-sentences',
    path: '/my-sentences',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMyMeaningsRoute = AuthenticatedMyMeaningsRouteImport.update({
  id: '/my-meanings',
  path: '/my-meanings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminMeaningsRoute =
  AuthenticatedAdminMeaningsRouteImport.update({
    id: '/admin/meanings',
    path: '/admin/meanings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/words': typeof WordsRoute
  '/my-meanings': typeof AuthenticatedMyMeaningsRoute
  '/my-sentences': typeof AuthenticatedMySentencesRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/test': typeof AuthenticatedTestRoute
  '/sentences/daily-use': typeof SentencesDailyUseRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/meanings': typeof AuthenticatedAdminMeaningsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/words': typeof WordsRoute
  '/my-meanings': typeof AuthenticatedMyMeaningsRoute
  '/my-sentences': typeof AuthenticatedMySentencesRoute
  '/practice': typeof AuthenticatedPracticeRoute
  '/test': typeof AuthenticatedTestRoute
  '/sentences/daily-use': typeof SentencesDailyUseRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/admin/meanings': typeof AuthenticatedAdminMeaningsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/words': typeof WordsRoute
  '/_authenticated/my-meanings': typeof AuthenticatedMyMeaningsRoute
  '/_authenticated/my-sentences': typeof AuthenticatedMySentencesRoute
  '/_authenticated/practice': typeof AuthenticatedPracticeRoute
  '/_authenticated/test': typeof AuthenticatedTestRoute
  '/sentences/daily-use': typeof SentencesDailyUseRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/_authenticated/admin/meanings': typeof AuthenticatedAdminMeaningsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/words'
    | '/my-meanings'
    | '/my-sentences'
    | '/practice'
    | '/test'
    | '/sentences/daily-use'
    | '/.lovable/oauth/consent'
    | '/admin/meanings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/words'
    | '/my-meanings'
    | '/my-sentences'
    | '/practice'
    | '/test'
    | '/sentences/daily-use'
    | '/.lovable/oauth/consent'
    | '/admin/meanings'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/words'
    | '/_authenticated/my-meanings'
    | '/_authenticated/my-sentences'
    | '/_authenticated/practice'
    | '/_authenticated/test'
    | '/sentences/daily-use'
    | '/.lovable/oauth/consent'
    | '/_authenticated/admin/meanings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WordsRoute: typeof WordsRoute
  SentencesDailyUseRoute: typeof SentencesDailyUseRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/words': {
      id: '/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof WordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentences/daily-use': {
      id: '/sentences/daily-use'
      path: '/sentences/daily-use'
      fullPath: '/sentences/daily-use'
      preLoaderRoute: typeof SentencesDailyUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/test': {
      id: '/_authenticated/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof AuthenticatedTestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/practice': {
      id: '/_authenticated/practice'
      path: '/practice'
      fullPath: '/practice'
      preLoaderRoute: typeof AuthenticatedPracticeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-sentences': {
      id: '/_authenticated/my-sentences'
      path: '/my-sentences'
      fullPath: '/my-sentences'
      preLoaderRoute: typeof AuthenticatedMySentencesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-meanings': {
      id: '/_authenticated/my-meanings'
      path: '/my-meanings'
      fullPath: '/my-meanings'
      preLoaderRoute: typeof AuthenticatedMyMeaningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/meanings': {
      id: '/_authenticated/admin/meanings'
      path: '/admin/meanings'
      fullPath: '/admin/meanings'
      preLoaderRoute: typeof AuthenticatedAdminMeaningsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMyMeaningsRoute: typeof AuthenticatedMyMeaningsRoute
  AuthenticatedMySentencesRoute: typeof AuthenticatedMySentencesRoute
  AuthenticatedPracticeRoute: typeof AuthenticatedPracticeRoute
  AuthenticatedTestRoute: typeof AuthenticatedTestRoute
  AuthenticatedAdminMeaningsRoute: typeof AuthenticatedAdminMeaningsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMyMeaningsRoute: AuthenticatedMyMeaningsRoute,
  AuthenticatedMySentencesRoute: AuthenticatedMySentencesRoute,
  AuthenticatedPracticeRoute: AuthenticatedPracticeRoute,
  AuthenticatedTestRoute: AuthenticatedTestRoute,
  AuthenticatedAdminMeaningsRoute: AuthenticatedAdminMeaningsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WordsRoute: WordsRoute,
  SentencesDailyUseRoute: SentencesDailyUseRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
